### ISSUE TITLE
OS X runtime error when running `ks init guestbook`

### ISSUE THREAD

**Issue by hausdorff** [ksonnet/ksonnet#129]
[Migrated from @rdodev https://github.com/ksonnet/ksonnet-lib/issues/86 ]

OS Version: OS X High Sierra
Shell: Bash 3.2
K8s version: 1.8, minikube

Tying to follow: https://ksonnet-next-site.i.heptio.com/docs/tutorial#1-initialize-your-app-commands

```
bash-3.2$ kubectl get namespaces
NAME          STATUS    AGE
default       Active    1h
ks-dev        Active    9m
kube-public   Active    1h
kube-system   Active    1h
```

`export GOPATH=/Users/ruben/go`

```bash-3.2$ ks init guestbook --context ks-dev
INFO  Using context 'ks-dev'
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1b805ce]

goroutine 1 [running]:
github.com/ksonnet/ksonnet/cmd.resolveContext(0xc420553ca8, 0xc420399800, 0x7, 0x7ffeefbffb54, 0x6, 0x0, 0x0)
    /Users/ruben/go/src/github.com/ksonnet/ksonnet/cmd/root.go:161 +0x3be
github.com/ksonnet/ksonnet/cmd.glob..func9(0x2528a00, 0xc42046eed0, 0x1, 0x3, 0x0, 0x0)
    /Users/ruben/go/src/github.com/ksonnet/ksonnet/cmd/init.go:68 +0x237
github.com/ksonnet/ksonnet/vendor/github.com/spf13/cobra.(*Command).execute(0x2528a00, 0xc42046ed80, 0x3, 0x3, 0x2528a00, 0xc42046ed80)
    /Users/ruben/go/src/github.com/ksonnet/ksonnet/vendor/github.com/spf13/cobra/command.go:656 +0x3f8
github.com/ksonnet/ksonnet/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x252b260, 0x10067ac, 0xc42006c058, 0x0)
    /Users/ruben/go/src/github.com/ksonnet/ksonnet/vendor/github.com/spf13/cobra/command.go:735 +0x339
github.com/ksonnet/ksonnet/vendor/github.com/spf13/cobra.(*Command).Execute(0x252b260, 0x0, 0x1e76419)
    /Users/ruben/go/src/github.com/ksonnet/ksonnet/vendor/github.com/spf13/cobra/command.go:694 +0x2b
main.main()
    /Users/ruben/go/src/github.com/ksonnet/ksonnet/main.go:33 +0x5b
```

**Comment by hausdorff** [comment]
In `root.go` we're doing this:

```
cluster, exists := rawConfig.Clusters[ctx.Cluster]
return cluster.Server, ctx.Namespace, nil
```

instead of this:

```
cluster, exists := rawConfig.Clusters[ctx.Cluster]
if !exists {
	return "", "", fmt.Errorf("No cluster with name '%s' exists", ctx.Cluster)
}
return cluster.Server, ctx.Namespace, nil
```

When `ctx.Cluster == ""` we can't find the cluster and we `nil` out.
