### ISSUE TITLE
ks init inside of dockerfile being built behind proxy fails

### ISSUE THREAD

**Issue by s1113950** [ksonnet/ksonnet#419]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
I got a large go stacktrace when running `ks init $APP_NAME`:

```
Step 18/29 : RUN ks init $APP_NAME
 ---> Running in 6e9552ff0ee2
Using context 'hyperkube' from the kubeconfig file specified at the environment variable $KUBECONFIG
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xedbae5]

goroutine 1 [running]:
github.com/ksonnet/ksonnet/client.(*Config).GetAPISpec(0xc420269220, 0xc4202c6620, 0x16, 0x0, 0x0)
	/Users/bryan/go/src/github.com/ksonnet/ksonnet/client/client.go:116 +0x2b5
github.com/ksonnet/ksonnet/cmd.glob..func12(0x1a3ac00, 0xc420310e80, 0x1, 0x1, 0x0, 0x0)
	/Users/bryan/go/src/github.com/ksonnet/ksonnet/cmd/init.go:84 +0x35d
github.com/ksonnet/ksonnet/vendor/github.com/spf13/cobra.(*Command).execute(0x1a3ac00, 0xc420310e40, 0x1, 0x1, 0x1a3ac00, 0xc420310e40)
	/Users/bryan/go/src/github.com/ksonnet/ksonnet/vendor/github.com/spf13/cobra/command.go:753 +0x468
github.com/ksonnet/ksonnet/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1a3db80, 0x13, 0x0, 0x0)
	/Users/bryan/go/src/github.com/ksonnet/ksonnet/vendor/github.com/spf13/cobra/command.go:843 +0x30a
github.com/ksonnet/ksonnet/vendor/github.com/spf13/cobra.(*Command).Execute(0x1a3db80, 0xc4200a2058, 0x0)
	/Users/bryan/go/src/github.com/ksonnet/ksonnet/vendor/github.com/spf13/cobra/command.go:791 +0x2b
main.main()
	/Users/bryan/go/src/github.com/ksonnet/ksonnet/main.go:35 +0x85
The command '/bin/sh -c ks init $APP_NAME' returned a non-zero code: 2
```

**What you expected to happen**:
I was able to create a new app

**How to reproduce it (as minimally and precisely as possible)**:
1. Put `ks init $APP_NAME` in a RUN call inside of a dockerfile
2. Call this to build:
```
docker build \
        --build-arg HTTP_PROXY=${HTTP_PROXY} \
        --build-arg HTTPS_PROXY=${HTTPS_PROXY} \
        --build-arg NO_PROXY=${NO_PROXY} \
        --build-arg http_proxy=${http_proxy} \
        --build-arg https_proxy=${https_proxy} \
        --build-arg no_proxy=${no_proxy} \
        -t sometag .
```

**Anything else we need to know?**:
Need to be behind a firewall probably. I'm at work and need those proxies to do anything.
I was also using hyperkube. This is my simple config:
```
apiVersion: v1
clusters:
- cluster:
    server: http://kubernetes:8080
  name: hyperkube
contexts:
- context:
    cluster: hyperkube
    user: hyperkube
  name: hyperkube
current-context: hyperkube
kind: Config
preferences: {}
```

If I remove the `--build-arg` flags then things work.

**Environment**:
- ksonnet version (use `ks version`): 0.9.2
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.3-gke.0", GitCommit:"a7b719f7d3463eb5431cf8a3caf5d485827b4210", GitTreeState:"clean", BuildDate:"2018-02-16T18:26:01Z", GoVersion:"go1.9.2b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by mmacvicar-splunk** [comment]
still occurring in 0.10.0. I can reproduce in an interactive docker shell (`docker exec -it`)

**Comment by bryanl** [comment]
I'm currently trying to reproduce this issue, so it can be diagnosed
